name: CICD

on:
  push: ['main']

jobs: 
  build:
    runs-on: [ubuntu-latest] 
    steps: 
      - name: Checkout source
        uses: action/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u HamidTech -p olalekan2019
      - name: Build Docker Image
        run: docker build -t taskmanagercontainer/task-manager .
      - name: Publish Image to Docker hub
        run: docker push taskmanagercontainer/task-manager:latest
  
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull  taskmanagercontainer/task-manager:latest
      - name: Delete old container
        run: docker rm -f task-manager-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name task-manager-container taskmanagercontainer/task-manager

