name: CICD

on:
  push:
    branches: [ master]

jobs: 
  build:
    runs-on: [ubuntu-latest] 
    steps: 
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u hamidtech -p olalekan2019
      - name: Build Docker Image
        run: docker build -t hamidtech/task-manager .
      - name: Publish Image to Docker hub
        run: docker push hamidtech/task-manager:latest
  
  deploy:
    needs: build
    runs-on: [aws-proj]
    steps:
      - name: Install docker
        run: |
          sudo apt update
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
      - name: Pull Image from docker hub
        run: docker pull  hamidtech/task-manager:latest
      - name: Delete old container
        run: docker rm -f task-manager-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name task-manager-container hamidtech/task-manager

